ci: add parsing the tests output
Removed the "git submodule" commands, by switching to a single .sh file. 
Adding task for executing and parsing the stdout of tests and providing the appropriate CI output.

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -15,11 +15,17 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Initialize submodule
-      run: git submodule init
+    - name: Initialize & update submodule
+      run: config.sh
 
-    - name: Update submodule
-      run: git submodule update
-
-    - name: Run tests
-      run: make test
+    - name: Run & parse Test Results
+      run: |
+        output=$(make test)
+        failures=$(echo "$output" | sed -n '/FAILURES:/,/-----------------------/p')
+        if [ -n "$failures" ]; then
+          echo "Test failures detected:"
+          echo "$failures" | grep -v "-----------------------"
+          exit 1
+        else
+          echo "All tests passed."
+        fi
