mb-feat: Add MacOS tests

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -1,4 +1,4 @@
-name: Makefile CI
+name: DSQ-test CI
 
 on:
   push:
@@ -8,28 +8,50 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-
+  build_linux:
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v3
-    
-    - name: Permission gived
-      # sudo in "actions" is paswordless
-      run: sudo chmod +x config.sh # i hope that is the last commit
-      
-    - name: Initialize & update submodule
-      run: ./config.sh
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Run & parse Test Results
-      run: |
-        output=$(make test)
-        failures=$(echo "$output" | sed -n '/FAILURES:/,/-----------------------/p')
-        if [ -n "$failures" ]; then
-          echo "Test failures detected:"
-          echo "$failures" | grep -v -- "-----------------------"
-          exit 1
-        else
-          echo "All tests passed."
-        fi
+      - name: Permission given
+        run: sudo chmod +x config.sh
+
+      - name: Initialize & update submodule
+        run: ./config.sh
+
+      - name: Run & parse Test Results
+        run: |
+          output=$(make test)
+          failures=$(echo "$output" | sed -n '/FAILURES:/,/-----------------------/p')
+          if [ -n "$failures" ]; then
+            echo "Test failures detected:"
+            echo "$failures" | grep -v -- "-----------------------"
+            exit 1
+          else
+            echo "All tests passed."
+          fi
+
+  build_macos:
+    runs-on: macos-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Permission given
+        run: chmod +x config.sh
+
+      - name: Initialize & update submodule
+        run: ./config.sh
+
+      - name: Run & parse Test Results
+        run: |
+          output=$(make test)
+          failures=$(echo "$output" | sed -n '/FAILURES:/,/-----------------------/p')
+          if [ -n "$failures" ]; then
+            echo "Test failures detected:"
+            echo "$failures" | grep -v -- "-----------------------"
+            exit 1
+          else
+            echo "All tests passed."
+          fi
